/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import br.ulbra.DAO.UsuarioDAO;
import br.ulbra.entity.Usuario;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Priscila Butzke
 */
public class FrUsuario extends javax.swing.JFrame {

    public void controlarBtn(int op) {
        switch (op) {
            case 1:
                pnCad.setVisible(false);
                btSalvar.setEnabled(true);
                break;
            case 2:
                pnCad.setVisible(true);
                btSalvar.setEnabled(true);
                btAlterar.setEnabled(false);
                btExcluir.setEnabled(false);
                break;
            case 3:
                pnCad.setVisible(true);
                btAlterar.setEnabled(true);
                btExcluir.setEnabled(true);
                btSalvar.setEnabled(false);
                break;
        }
        this.pack();
    }

    /**
     * Creates new form FrCadastro
     */
    public FrUsuario() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);//centraliza no centro da tela ao executar
        controlarBtn(1);
        readJTable();
        edCod.setEnabled(false);
    }

    public void readJTable() throws SQLException {
        DefaultTableModel modelo = (DefaultTableModel) tbUsuario.getModel();
        modelo.setNumRows(0);
        UsuarioDAO udao = new UsuarioDAO();
        for (Usuario p : udao.read()) {
            modelo.addRow(new Object[]{
                p.getIdUsu(),
                p.getNomeUsu(),
                p.getEmailUsu(),
                p.getSenhaUsu(),
                p.getFoneUsu(),
                p.getSexoUsu()
            });
        }
    }

    public void readJTableForDesc(String nome) throws SQLException {
        DefaultTableModel modelo
                = (DefaultTableModel) tbUsuario.getModel();
        modelo.setNumRows(0);
        UsuarioDAO pdao = new UsuarioDAO();
        for (Usuario p : pdao.readForDesc(nome)) {
            modelo.addRow(new Object[]{
                p.getIdUsu(),
                p.getNomeUsu(),
                p.getEmailUsu(),
                p.getSenhaUsu(),
                p.getFoneUsu(),
                p.getSexoUsu()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        huj = new javax.swing.JPanel();
        pnCad = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rbM = new javax.swing.JRadioButton();
        rbF = new javax.swing.JRadioButton();
        rbO = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        edSenha2 = new javax.swing.JPasswordField();
        edCod = new javax.swing.JTextField();
        edNome = new javax.swing.JTextField();
        edEmail = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        edSenha1 = new javax.swing.JPasswordField();
        edFone = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsuario = new javax.swing.JTable();
        btNovo = new javax.swing.JButton();
        edPesquisa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        huj.setBackground(new java.awt.Color(204, 204, 255));

        pnCad.setBackground(new java.awt.Color(255, 129, 79));
        pnCad.setForeground(new java.awt.Color(255, 129, 79));
        pnCad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/artboard-12_89035.png"))); // NOI18N
        pnCad.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 140, 160));

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cod");
        pnCad.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nome");
        pnCad.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 7, -1, 30));

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("E-mail");
        pnCad.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Telefone");
        pnCad.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Sexo");
        pnCad.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, 30));

        rbM.setBackground(new java.awt.Color(255, 129, 79));
        buttonGroup1.add(rbM);
        rbM.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        rbM.setForeground(new java.awt.Color(0, 0, 0));
        rbM.setSelected(true);
        rbM.setText("Masculino");
        rbM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMActionPerformed(evt);
            }
        });
        pnCad.add(rbM, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        rbF.setBackground(new java.awt.Color(255, 129, 79));
        buttonGroup1.add(rbF);
        rbF.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        rbF.setForeground(new java.awt.Color(0, 0, 0));
        rbF.setText("Feminino");
        pnCad.add(rbF, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        rbO.setBackground(new java.awt.Color(255, 129, 79));
        buttonGroup1.add(rbO);
        rbO.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        rbO.setForeground(new java.awt.Color(0, 0, 0));
        rbO.setText("Outros");
        pnCad.add(rbO, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Senha");
        pnCad.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        edSenha2.setBackground(new java.awt.Color(255, 255, 204));
        edSenha2.setForeground(new java.awt.Color(0, 0, 0));
        pnCad.add(edSenha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 210, 30));

        edCod.setBackground(new java.awt.Color(255, 255, 204));
        edCod.setForeground(new java.awt.Color(0, 0, 0));
        pnCad.add(edCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 130, 30));

        edNome.setBackground(new java.awt.Color(255, 255, 204));
        edNome.setForeground(new java.awt.Color(0, 0, 0));
        edNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edNomeActionPerformed(evt);
            }
        });
        pnCad.add(edNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 460, 30));

        edEmail.setBackground(new java.awt.Color(255, 255, 204));
        edEmail.setForeground(new java.awt.Color(0, 0, 0));
        pnCad.add(edEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 410, 30));

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salvar.png"))); // NOI18N
        btSalvar.setText("SALVAR");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        pnCad.add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 120, 40));

        btAlterar.setBackground(new java.awt.Color(255, 129, 79));
        btAlterar.setForeground(new java.awt.Color(255, 129, 79));
        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-engrenagem-30.png"))); // NOI18N
        btAlterar.setToolTipText("");
        btAlterar.setBorder(null);
        btAlterar.setBorderPainted(false);
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });
        pnCad.add(btAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 40, 40));

        btExcluir.setBackground(new java.awt.Color(255, 129, 79));
        btExcluir.setForeground(new java.awt.Color(255, 129, 79));
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lixeira.png"))); // NOI18N
        btExcluir.setBorder(null);
        btExcluir.setBorderPainted(false);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        pnCad.add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 40, 40));

        edSenha1.setBackground(new java.awt.Color(255, 255, 204));
        edSenha1.setForeground(new java.awt.Color(0, 0, 0));
        pnCad.add(edSenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 190, 30));

        edFone.setBackground(new java.awt.Color(255, 255, 204));
        try {
            edFone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)# ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnCad.add(edFone, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 89, 130, 30));

        jPanel1.setBackground(new java.awt.Color(255, 129, 79));
        jPanel1.setForeground(new java.awt.Color(255, 129, 79));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbUsuario.setBackground(new java.awt.Color(255, 129, 79));
        tbUsuario.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        tbUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cod", "Nome", "E-mail", "Senha", "Fone", "Sexo"
            }
        ));
        tbUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbUsuario);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 690, 190));

        btNovo.setText("NOVO");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        jPanel1.add(btNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 100, 40));

        edPesquisa.setBackground(new java.awt.Color(255, 255, 204));
        edPesquisa.setForeground(new java.awt.Color(0, 0, 0));
        edPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edPesquisaActionPerformed(evt);
            }
        });
        jPanel1.add(edPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 490, 30));

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cadastro de Usuários");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 129, 79));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loupe_79257.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        javax.swing.GroupLayout hujLayout = new javax.swing.GroupLayout(huj);
        huj.setLayout(hujLayout);
        hujLayout.setHorizontalGroup(
            hujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hujLayout.createSequentialGroup()
                .addComponent(pnCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        hujLayout.setVerticalGroup(
            hujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hujLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnCad, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(huj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(huj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMActionPerformed

    private void edNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edNomeActionPerformed

    public boolean useRegex(String input) {
        // Compile regular expression
        Pattern pattern = Pattern.compile("[a-zA-Z]+@[a-zA-Z]+\\.[a-zA-Z]+", Pattern.CASE_INSENSITIVE);
        // Match regex against input
        Matcher matcher = pattern.matcher(input);
        // Use results...
        return matcher.matches();
    }
    
    private boolean ehEmailValido(String email) {
        JOptionPane.showMessageDialog(null,  useRegex(email));
        if (useRegex(email)) {
            return true;
        } else {
            JOptionPane.showMessageDialog(null,
                    "Email inválido.");
            return false;
        }
    }

    private boolean ehSenhaValida(String senha, String senha2) {
        if (senha.equals(senha2)) {
            return true;

        } else {
            JOptionPane.showMessageDialog(null,
                    "Você inseriu senhas diferentes!");
            return false;
        }
    }

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed

        Usuario u = new Usuario();
        try {
            UsuarioDAO ud = new UsuarioDAO();
            if (!edNome.getText().isEmpty()
                    && !edEmail.getText().isEmpty()
                    && !edSenha1.getText().isEmpty()
                    && !edSenha2.getText().isEmpty()
                    && !edFone.getText().isEmpty()) {

                u.setNomeUsu(edNome.getText());
                u.setEmailUsu(edEmail.getText());
                u.setSenhaUsu(edSenha1.getText());
                u.setFoneUsu(edFone.getText());
                if (rbM.isSelected()) {
                    u.setSexoUsu(1);
                } else if (rbF.isSelected()) {
                    u.setSexoUsu(2);
                } else {
                    u.setSexoUsu(3);
                }
                
                if(ehSenhaValida(edSenha1.getText(),edSenha2.getText()) && ehEmailValido(edEmail.getText())){
                    ud.create(u);
                    controlarBtn(1);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
        }

       
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        controlarBtn(1);

        Usuario u = new Usuario();
        try {
            UsuarioDAO ud = new UsuarioDAO();

            u.setNomeUsu(edNome.getText());
            u.setIdUsu(Integer.parseInt(edCod.getText()));
            u.setEmailUsu(edEmail.getText());
            u.setSenhaUsu(edSenha1.getText());
            u.setSenhaUsu(edSenha2.getText());
            u.setFoneUsu(edFone.getText());
            if (rbM.isSelected()) {
                u.setSexoUsu(1);
            } else if (rbF.isSelected()) {
                u.setSexoUsu(2);
            } else {
                u.setSexoUsu(3);
            }
            if (edSenha1.getText().equals(edSenha2.getText())) {
                ud.update(u);
                readJTable();
            } else {
                JOptionPane.showMessageDialog(null,
                        "Você inseriu senhas diferentes!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
        }


    }//GEN-LAST:event_btAlterarActionPerformed

    private void edPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edPesquisaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            readJTableForDesc(edPesquisa.getText());
        } catch (SQLException ex) {
            Logger.getLogger(FrUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        controlarBtn(2);

        edNome.setText("");
        edEmail.setText("");
        edSenha1.setText("");
        edSenha2.setText("");
        edFone.setText("");
        rbO.setSelected(true);
    }//GEN-LAST:event_btNovoActionPerformed

    private void tbUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUsuarioMouseClicked
        controlarBtn(3);

        //puxa as informações do banco de dados
        if (tbUsuario.getSelectedRow() != -1) {

            //seta as informações do banco nas linhas da tabela da view, em ordem de colunas
            edCod.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 0).toString());
            edNome.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 1).toString());
            edEmail.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 2).toString());
            edSenha1.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 3).toString());
            edSenha2.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 3).toString());
            edFone.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 4).toString());
            int s = (int) tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 5);

            if (s == 1) {
                rbM.setSelected(true);
            } else if (s == 2) {
                rbF.setSelected(true);
            } else {
                rbO.setSelected(true);
            }

        }
    }//GEN-LAST:event_tbUsuarioMouseClicked

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        controlarBtn(1);
        Usuario u = new Usuario();
        try {
            UsuarioDAO ud = new UsuarioDAO();
            u.setIdUsu(Integer.parseInt(edCod.getText()));
            ud.delete(u);
            readJTable();

        } catch (SQLException ex) {
            Logger.getLogger(FrUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrUsuario().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FrUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField edCod;
    private javax.swing.JTextField edEmail;
    private javax.swing.JFormattedTextField edFone;
    private javax.swing.JTextField edNome;
    private javax.swing.JTextField edPesquisa;
    private javax.swing.JPasswordField edSenha1;
    private javax.swing.JPasswordField edSenha2;
    private javax.swing.JPanel huj;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnCad;
    private javax.swing.JRadioButton rbF;
    private javax.swing.JRadioButton rbM;
    private javax.swing.JRadioButton rbO;
    private javax.swing.JTable tbUsuario;
    // End of variables declaration//GEN-END:variables
}
